---
kind: pipeline
type: docker
name: default-build

steps:
  - name: build
    image: golang:1.14.2
    commands:
      - apt-get update && apt-get install -y cmake
      - make test
      - make build
  - name: publish-docker
    image: plugins/docker:18
    settings:
      dockerfile: .drone/Dockerfile
      repo: publicawesome/gaia
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - gz-3-stakebird
    when:
      branch:
        - gz-3-stakebird
      event:
        - push
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]
---
kind: signature
hmac: d380c16d9790dc7a3f880ae8e0f6c480d54a3de77e4cc3895ac34d2b1f7ccc05

...
